version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: m38978234_nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php"
    volumes:
      - ../var/log/nginx:/var/log/nginx
      - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/includes:/etc/nginx/includes
      - ./config/nginx/custom-locations:/etc/nginx/custom-locations
    volumes_from:
      - php

  php:
    build: docker-images/php
    container_name: m38978234_php
    links:
      - "mysql:mysql"
    volumes:
      - ..:/var/www/html
      - ../var:/var/www/html/var

  mysql:
    image: mysql:5.6
    container_name: m38978234_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pw
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/dumps:/home/dumps

  redis:
    image: redis
    container_name: m38978234_redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: m38978234_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  memcached:
    image: memcached
    container_name: m38978234_memcached
    ports:
      - "11211:11211"

  varnish:
    build: docker-images/varnish
    container_name: m38978234_varnish
    volumes:
      - ./config/varnish/etc:/etc/varnish