version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php"
    volumes:
      - ../var/log/nginx:/var/log/nginx
      - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/includes:/etc/nginx/includes
      - ./config/nginx/custom-locations:/etc/nginx/custom-locations
    volumes_from:
      - php
  php:
    build: docker-images/php
    links:
      - "mysql:mysql"
    volumes:
      - ..:/var/www/html
  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pw
    volumes:
      - ../var/data/mysql:/var/lib/mysql